"""added created_at to Participant

Revision ID: 712466f998a9
Revises: 0e01a187ae03
Create Date: 2024-10-25 16:16:19.937765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '712466f998a9'
down_revision: Union[str, None] = '0e01a187ae03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'created_at')
    # ### end Alembic commands ###
