"""added estimates_number to Participant

Revision ID: e84765465760
Revises: 712466f998a9
Create Date: 2024-10-26 09:16:51.779499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e84765465760'
down_revision: Union[str, None] = '712466f998a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('estimates_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'estimates_number')
    # ### end Alembic commands ###
