"""added longitude and latitude to Participant

Revision ID: fec1b96d8ce1
Revises: e84765465760
Create Date: 2024-10-27 08:05:22.131840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec1b96d8ce1'
down_revision: Union[str, None] = 'e84765465760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('participants', sa.Column('latitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    # обновляем существующих участников
    op.execute(
        """
        UPDATE participants
        SET 
            longitude = RANDOM() * 199 + 1,
            latitude = RANDOM() * 199 + 1
        """
    )

    op.alter_column('participants', 'longitude', nullable=False)
    op.alter_column('participants', 'latitude', nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'latitude')
    op.drop_column('participants', 'longitude')
    # ### end Alembic commands ###
